version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:8001'
      - '3001:3001'
    volumes:
      - ./server:/app/server
      - ./client:/app/client